import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path"; import { describe, it } from "node:test";
const root = path.resolve(process.cwd(), "src/app/api/trainings"); const read = (name: string) => fs.readFileSync(path.join(root, name), "utf8");
describe("training route contracts", () => {
  it("gates every route and authenticates mutations before body reads", () => { for (const file of ["route.ts", "[id]/route.ts", "[id]/publication/route.ts"]) { const source = read(file); assert.ok(source.indexOf('featureFlag("FEATURE_ANCILLARY")') < source.indexOf("request.json()")); if (source.includes("request.json()")) assert.ok(source.indexOf("requireRole") < source.indexOf("request.json()")); } });
  it("awaits dynamic params and exposes inert bootstrap fields", () => { for (const file of ["[id]/route.ts", "[id]/publication/route.ts"]) assert.match(read(file), /await context\.params/); const config = read("config/route.ts"); assert.match(config, /enabled: false/); assert.match(config, /attestationAvailable: false/); assert.match(config, /northwestPartnerUrl: null/); });
  it("requires an exact admin reason only after auth and the console flag", () => { const source = read("[id]/publication/route.ts"); const admin = source.indexOf('session.role === "platform_admin"'); assert.ok(source.indexOf("requireRole") < source.indexOf("request.json()")); assert.ok(admin < source.indexOf('featureFlag("FEATURE_CONSOLE_OPS")', admin)); assert.match(source, /Object\.keys\(value\)\.length !== 1/); assert.match(source, /unpublishTraining\(session, id, value\.reason\)/); assert.match(source, /trainingResponse\(await unpublishTraining\(session, id\), false\)/); });
  it("keeps the disabled config envelope free of child capability fields", () => { const config = read("config/route.ts"); const disabled = config.slice(0, config.indexOf("try")); assert.doesNotMatch(disabled, /consoleOpsEnabled/); });
  it("accepts admin source files only through exact multipart forms while operator writes remain JSON", () => { const create = read("route.ts"); const update = read("[id]/route.ts"); for (const source of [create, update]) { assert.match(source, /session\.role === "platform_admin"/); assert.match(source, /startsWith\("multipart\/form-data;"\)/); assert.match(source, /parsePlatformTrainingForm/); assert.match(source, /trainingSourceInputFromFile/); assert.match(source, /startsWith\("application\/json"\)/); } assert.match(create, /parsePlatformTrainingForm\(form, true\)/); assert.match(update, /parsePlatformTrainingForm\(form, false\)/); });
  it("keeps private source coordinates off responses and exposes one admin-only download route", () => { for (const file of ["route.ts", "[id]/route.ts", "[id]/publication/route.ts"]) assert.match(read(file), /trainingResponse/); const source = read("[id]/source/route.ts"); assert.match(source, /requireRole\("platform_admin"\)/); assert.match(source, /downloadPlatformTrainingSource\(session, id\)/); assert.match(source, /"Cache-Control": "private, no-store"/); assert.match(source, /"X-Content-Type-Options": "nosniff"/); assert.doesNotMatch(source, /searchParams|bucket|objectPath|createSignedUrl|getPublicUrl/); });
});
