import { featureFlag } from "@/lib/env";
import { disabled, failure, invalid, json, UUID } from "@/lib/ancillary/http";
const SECTIONS = ["articles", "ein", "tax_returns", "bank_statements", "other"] as const;
export async function GET(request: Request) {
  if (!featureFlag("FEATURE_ANCILLARY")) return disabled(); const clientId = new URL(request.url).searchParams.get("clientId"); if (!clientId || !UUID.test(clientId)) return invalid();
  try { const [{ getSession }, { clientReachable }, { listCompanyDocuments }] = await Promise.all([import("@/lib/auth/session"), import("@/lib/applications/access"), import("@/lib/ancillary/company-uploads")]); const session = await getSession(); if (!session) return json({ error: "authentication_required" }, 401); if (!(await clientReachable(session, clientId))) return json({ error: "not_found" }, 404); return json({ documents: await listCompanyDocuments(clientId) }); } catch (error) { return failure(error); }
}
export async function POST(request: Request) {
  if (!featureFlag("FEATURE_ANCILLARY")) return disabled(); const params = new URL(request.url).searchParams; const clientId = params.get("clientId"); const section = params.get("section"); if (!clientId || !UUID.test(clientId) || !SECTIONS.includes(section as (typeof SECTIONS)[number])) return invalid();
  try { const [{ getSession }, { assertTenantWriteAllowed }, { clientReachable }, { uploadCompanyDocument }, { readPortalPreferencesForOrg }] = await Promise.all([import("@/lib/auth/session"), import("@/lib/tenancy/wall"), import("@/lib/applications/access"), import("@/lib/ancillary/company-uploads"), import("@/lib/portal/preferences.server")]); const session = await getSession(); if (!session) return json({ error: "authentication_required" }, 401); if ((session.role !== "consumer" && session.role !== "operator_member") || !session.orgId) return json({ error: "forbidden" }, 403); await assertTenantWriteAllowed(session); if (!(await clientReachable(session, clientId))) return json({ error: "not_found" }, 404); if (session.role === "consumer" && !(await readPortalPreferencesForOrg(session.orgId)).portal.allowDocumentUploads) return json({ error: "uploads_disabled_by_workspace" }, 403);
    const form = await request.formData(); const entries = [...form.getAll("files"), ...form.getAll("file")]; if (entries.length === 0 || entries.some((entry) => !(entry instanceof File))) return invalid(); const documents = []; for (const entry of entries as File[]) documents.push(await uploadCompanyDocument({ orgId: session.orgId, clientId, actorId: session.id, section: section as (typeof SECTIONS)[number], fileName: entry.name, mimeType: entry.type, bytes: new Uint8Array(await entry.arrayBuffer()) })); return json({ documents }, 201);
  } catch (error) { return failure(error); }
}
